export default function FilesPage() {
  return (
    <section className="page-panel">
      <header className="page-header">
        <div>
          <span className="eyebrow">Files</span>
          <h1>Personal files first, team sharing second.</h1>
          <p>
            This tab is the safe interface over uploads, generated artifacts, and explicit
            sharing. Participants should never need raw access to the OpenClaw workspace.
          </p>
        </div>
      </header>

      <div className="files-grid">
        <article className="content-card">
          <h2>My files</h2>
          <ul>
            <li>`brief-v2.docx` — uploaded by participant</li>
            <li>`kickoff-outline.md` — generated by personal agent</li>
            <li>`research-notes.pdf` — shared into team workspace</li>
          </ul>
          <div className="inline-actions">
            <button className="primary-button" type="button">
              Upload file
            </button>
            <button className="secondary-button" type="button">
              Download selected
            </button>
          </div>
        </article>

        <article className="content-card">
          <h2>Storage plan</h2>
          <ul>
            <li>Start with local disk on Hetzner.</li>
            <li>Track file metadata in Postgres.</li>
            <li>Add object storage later if volume grows.</li>
          </ul>
        </article>
      </div>
    </section>
  );
}
